// src/app/pages/wip/page.tsx
import Image from "next/image";
import wip from "./wip.png";
import Link from "next/link";

export default function WorkInProgressPage() {
  return (
    <Link href="/">
      <Image
        src={wip}
        alt="Work in progress!"
        draggable={false}
        className="max-h-[60vh] w-auto mx-auto"
      />
    </Link>
  );
}

// app/pages/pages/wip.vue
<script lang="ts" setup>
definePageMeta({
  title: 'Work in progress!'
});

defineRouteRules({
  prerender: true
});
</script>

<template>
  <PageLayout>
    <NuxtLink
      href="/"
      aria-label="Home"
    >
      <NuxtImg
        src="/wip/wip.png"
        alt="Work in progress!"
        draggable="false"
        class="max-h-[60vh] w-auto mx-auto"
      />
    </NuxtLink>
  </PageLayout>
</template>
